import { NextResponse } from "next/server";

export const dynamic = "force-static";

export async function GET() {
  const content = `# SendQuote — AI-Powered Revenue Workflow Platform

## Overview
SendQuote is an AI-powered quotation platform for Indian businesses. Generate GST-ready quotes, send interactive deal rooms, collect e-signatures, and close deals faster — all in one place.

## Quick Facts
- **Founded**: 2025
- **HQ**: India
- **Pricing**: Free (Starter), ₹6,499/yr (Growth), ₹16,499/yr (Pro)
- **Target Audience**: Indian SMEs, agencies, consultants, freelancers, SaaS companies, manufacturers
- **Key Differentiator**: Built specifically for Indian businesses with GST compliance, INR pricing, UPI/Razorpay payments
- **AI Models**: Groq (primary, llama-3.3-70b), Gemini (fallback)
- **Tech Stack**: Next.js 16, Supabase, Tailwind CSS v4, Razorpay, Resend, Sentry, PostHog, Vercel

## Key Capabilities
- **AI Quote Generation**: Generate complete quotes from a brief description in under 60 seconds using Groq/LLM
- **Interactive Deal Room**: Branded, responsive quote pages with real-time buyer analytics
- **Buyer Intent Tracking**: Track opens, section-level engagement, device type, location, and revisit patterns
- **In-Quote Negotiation**: Buyers can request changes, adjust quantities, and counter-offer inside the quote
- **One-Click E-Signature**: Native signature collection (canvas-based) without redirects
- **Payment Collection**: Accept payments via Razorpay (India - UPI, cards, netbanking) and Stripe (global)
- **Approval Workflows**: Rule-based discount and deal approval routing (manager, director, VP)
- **AI Auto Follow-Ups**: Personalized follow-up emails generated by Groq based on buyer behavior
- **CRM Sync**: Bi-directional sync with HubSpot, Salesforce, and Pipedrive
- **Contract Automation**: Signed quotes auto-convert to contracts and invoices
- **Client Portal**: Single dashboard view of all quotes, contracts, invoices, and payments
- **Currency**: INR (Indian Rupee)
- **AI Deal Copilot**: Per-quote scoring (0-100) with contextual suggestions
- **Team Collaboration**: Role-based team management with invite system
- **Multi-language**: English, Hindi, Marathi
- **Quote Templates**: Customizable templates with business branding
- **Scheduling**: Automated follow-up scheduling with cron-based reminders

## Pricing Plans (Annual, INR)
| Plan | Price | Quotes/mo | AI Features | Team | Support |
|------|-------|-----------|-------------|------|---------|
| Starter | Free | 50 | Basic | 1 user | Community |
| Growth | ₹6,499/yr | Unlimited | Full AI | 5 users | Email |
| Pro | ₹16,499/yr | Unlimited | Full AI + Copilot | Unlimited | Priority |

## API Reference
Base URL: https://sendquote.in/api

### Quotes
- GET /api/quotes — List all quotes
- POST /api/quotes — Create a new quote
- GET /api/quotes/[id] — Get quote details with line items
- PATCH /api/quotes/[id] — Update quote status
- DELETE /api/quotes/[id] — Delete quote
- POST /api/quotes/send — Send quote via email
- POST /api/quotes/accept — Accept quote with e-signature (public)

### AI
- POST /api/ai/generate — Generate quote from description
- POST /api/ai/followup — Generate AI follow-up email
- POST /api/ai/copilot — Analyze deal and get suggestions

### Chat (Deal Room)
- GET /api/chat?quote_id=X — List chat messages (auth required)
- POST /api/chat — Send message as seller (auth required)
- POST /api/chat/buyer — Send message as buyer (public token)

### Clients & Invoices
- GET /api/clients — List clients
- POST /api/clients — Create client
- GET /api/invoices — List invoices

### Analytics & Admin
- GET /api/analytics — Aggregate quote analytics
- GET /api/admin/stats — Admin dashboard stats

### Payments & Subscriptions
- POST /api/payments/razorpay — Create Razorpay payment order
- POST /api/subscriptions — Manage subscriptions
- POST /api/webhook/razorpay — Razorpay webhook handler (HMAC signed)

### Integrations
- POST /api/crm/sync — Sync quote to connected CRM
- POST /api/webhooks/n8n — Webhook endpoint for n8n automation

### Other
- GET /api/health — Health check
- POST /api/portal — Client portal lookup by email
- POST /api/voice — AI voice assistant
- POST /api/events — Track buyer events

## Authentication
- Supabase Auth for user accounts
- Google SSO and email/password login
- JWT-based session management (1 hour expiry)
- Service role key for admin operations
- Plan-based access control (starter, growth, pro, enterprise)

## Key Integrations
- **CRM**: HubSpot, Pipedrive
- **AI**: Groq (llama-3.3-70b), Gemini (fallback)
- **Email**: Resend (transactional)
- **Payments**: Razorpay (India), Stripe (global)
- **Workflows**: n8n
- **Analytics**: PostHog, Vercel Analytics
- **Monitoring**: Sentry (error tracking)
- **Auth**: Supabase Auth
- **AI Crawlers**: Allowed (GPTBot, Claude-Web, PerplexityBot, Google-Extended)

## Database Schema (Supabase PostgreSQL)
### Core Tables
- profiles — User profiles with plan, billing, GST info
- quotes — Quote records with status workflow (draft, sent, opened, accepted, changes_requested, expired, archived, lost)
- quote_items — Line items per quote
- quote_events — Buyer event tracking (viewed, pricing_viewed, signed)
- quote_signatures — E-signature data

### Billing
- invoices — Auto-generated from accepted quotes
- invoice_items — Invoice line items
- payments — Payment tracking
- subscriptions — Razorpay subscription management

### CRM & Workflow
- clients — Client records with aggregated stats
- leads — Landing page leads
- approval_rules — Discount/approval threshold rules
- approval_requests — Pending approval requests
- deal_room_messages — In-quote chat messages
- cron_reminders — Scheduled follow-ups

### System
- admin_audit_log — Admin action tracking
- error_logs — System error capture
- rate_limits — API rate limiting data
- feature_flags — Feature toggles
- activity_logs — Audit trail
- analytics_events — Product analytics
- webhook_events — Incoming webhook dedup

## Deployment
- Hosted on Vercel (Edge Network)
- Database: Supabase PostgreSQL
- Auth: Supabase Auth
- Monitoring: Sentry
- Domain: sendquote.in (India-focused)
- CI/CD: GitHub Actions → test → deploy → smoke tests → notify

## Common Questions (FAQ)
- **What is SendQuote?**: AI-powered quoting platform for Indian businesses.
- **How does AI quote generation work?**: Describe your project briefly — AI generates complete line items, pricing, terms, and notes in under 60 seconds.
- **Can I accept payments inside the quote?**: Yes — integrated Razorpay and Stripe allow buyers to sign and pay in one click. Supports credit cards, UPI, and bank transfers.
- **Which CRMs do you integrate with?**: HubSpot, Salesforce, and Pipedrive with bi-directional sync.
- **Is there a free plan?**: Yes — Starter plan is free with 50 quotes/month, basic templates, e-signature, and buyer tracking.
- **Do you support GST invoices?**: Yes — GST rates and amounts are built into quotes and invoices.
- **What payment providers are supported?**: Razorpay for India (UPI, cards, net banking) and Stripe for international.

## Documentation
- Help Center: https://sendquote.in/docs
- Blog: https://sendquote.in/blog
- Changelog: https://sendquote.in/changelog
- FAQ: https://sendquote.in/faq
- Pricing: https://sendquote.in/pricing
- Privacy: https://sendquote.in/privacy
- Terms: https://sendquote.in/terms

## Contact
- Website: https://sendquote.in
- Support: support@sendquote.in
- Twitter/X: @sendquote

## Changelog Highlights
- v2.0.0: Admin dashboard, audit logging, plan gates, voice assistant, deal copilot, approval workflows
- v1.0.0: Initial launch — AI quotes, Deal Room, payments, e-signature, CRM sync, analytics, multi-language

## Entity Relationships
- User → Organization → Quotes → Line Items
- User → Organization → Clients → Quotes
- Quote → Invoice → Payment
- Quote → Quote Events (tracking)
- Quote → Deal Room Messages (chat)
- User → Approval Rules → Approval Requests
`;
  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
