import { NextResponse } from "next/server";

export const dynamic = "force-static";

export async function GET() {
  const content = `# SendQuote — AI-Powered Revenue Workflow Platform

## Overview
SendQuote is an AI-powered quotation and revenue workflow platform that helps businesses generate, negotiate, approve, and close deals in hours instead of weeks. It transforms static PDF quotes into interactive, trackable buying experiences with built-in AI, e-signature, payment collection, and CRM sync.

## Key Capabilities
- **AI Quote Generation**: Generate complete quotes from a brief description in under 60 seconds using Groq/LLM
- **Interactive Deal Room**: Branded, responsive quote pages with real-time buyer analytics
- **Buyer Intent Tracking**: Track opens, section-level engagement, device type, location, and revisit patterns
- **In-Quote Negotiation**: Buyers can request changes, adjust quantities, and counter-offer inside the quote
- **One-Click E-Signature**: Native signature collection (canvas-based) without redirects
- **Payment Collection**: Accept payments via Razorpay (India - UPI, cards, netbanking) and Stripe (global)
- **Approval Workflows**: Rule-based discount and deal approval routing (manager → director → VP)
- **AI Auto Follow-Ups**: Personalized follow-up emails generated by Groq based on buyer behavior
- **CRM Sync**: Bi-directional sync with HubSpot, Salesforce, and Pipedrive
- **Contract Automation**: Signed quotes auto-convert to contracts and invoices
- **Client Portal**: Single dashboard view of all quotes, contracts, invoices, and payments
- **Multi-Currency**: INR, USD, EUR, GBP, AED, SGD
- **AI Deal Copilot**: Per-quote scoring (0-100) with contextual suggestions

## API Reference
Base URL: https://sendquote.in/api

### Quotes
- \`GET /api/quotes\` — List all quotes
- \`POST /api/quotes\` — Create a new quote
- \`GET /api/quotes/[id]\` — Get quote details with line items
- \`PATCH /api/quotes/[id]\` — Update quote status
- \`POST /api/quotes/send\` — Send quote via email
- \`POST /api/quotes/accept\` — Accept quote with e-signature
- \`POST /api/quotes/accept-payment\` — Record payment against accepted quote

### AI
- \`POST /api/ai/generate\` — Generate quote from description
- \`POST /api/ai/followup\` — Generate AI follow-up email
- \`POST /api/ai/copilot\` — Analyze deal and get suggestions

### CRM
- \`POST /api/crm/sync\` — Sync quote to connected CRM
- \`POST /api/webhooks/n8n\` — Webhook endpoint for n8n automation

### Payments
- \`POST /api/payments/razorpay\` — Create Razorpay order
- \`POST /api/payments/stripe\` — Create Stripe payment intent
- \`POST /api/webhook/razorpay\` — Razorpay webhook handler

### Clients & Invoices
- \`GET /api/clients\` — List clients
- \`POST /api/clients\` — Create client
- \`GET /api/invoices\` — List invoices

### Analytics
- \`GET /api/analytics\` — Aggregate quote analytics
- \`POST /api/portal\` — Client portal data by email

### Health
- \`GET /api/health\` — Health check endpoint

## Authentication
- Supabase Auth for user accounts
- Google SSO and email/password login
- JWT-based session management
- RBAC: admin, member, viewer roles

## Key Integrations
- **Payments**: Razorpay (India), Stripe (Global)
- **CRM**: HubSpot, Salesforce, Pipedrive
- **AI**: Groq (Mixtral 8x7B), Gemini (fallback)
- **Email**: Resend (transactional)
- **Workflows**: n8n (self-hosted)
- **Analytics**: PostHog
- **Monitoring**: Sentry
- **Auth**: Supabase Auth

## Deployment
- Hosted on Vercel (Edge Network)
- Database: Supabase PostgreSQL
- Cache: Upstash Redis
- Domain: sendquote.in

## Documentation
- Help Center: https://sendquote.in/docs
- Blog: https://sendquote.in/blog
- Changelog: https://sendquote.in/changelog
- FAQ: https://sendquote.in/faq
- Pricing: https://sendquote.in/pricing
- Privacy: https://sendquote.in/privacy
- Terms: https://sendquote.in/terms

## Contact
- Website: https://sendquote.in
- Support: support@sendquote.in
- Twitter/X: @sendquote

## Changelog Highlights
- v1.0.0 (2026-06-06): Initial launch — AI quotes, Deal Room, payments, e-signature, CRM sync, analytics, multi-currency

## Entity Relationships
- User → Organization → Quotes → Line Items
- User → Organization → Clients → Quotes
- Quote → Invoice → Payment
- Quote → Quote Events (tracking)
- Quote → Deal Room Messages (chat)
- User → Approval Rules → Approval Requests
`;
  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
