export interface ContractData {
  quoteNumber: string;
  clientName: string;
  clientEmail: string | null;
  businessName: string;
  items: { description: string; quantity: number; rate: number; amount: number }[];
  subtotal: number;
  gstRate: number;
  gstAmount: number;
  total: number;
  notes: string | null;
  terms: string | null;
  signatoryName: string;
  signedAt: string;
  validUntil: string | null;
}

export function generateContractHtml(data: ContractData): string {
  const itemsRows = data.items.map((item) => `
    <tr>
      <td style="padding:8px;border-bottom:1px solid #e5e7eb">${item.description}</td>
      <td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:center">${item.quantity}</td>
      <td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:right">$${item.rate.toFixed(2)}</td>
      <td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:right">$${item.amount.toFixed(2)}</td>
    </tr>
  `).join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Inter', Arial, sans-serif; color: #1e293b; font-size: 14px; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 24px; margin-bottom: 12px; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th { background: #f8fafc; padding: 8px; text-align: left; font-weight: 600; border-bottom: 2px solid #e5e7eb; }
    .total-row { font-weight: bold; font-size: 16px; }
    .signature-box { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-top: 24px; background: #fafafa; }
    .stamp { color: #2563eb; font-size: 32px; font-weight: bold; opacity: 0.3; transform: rotate(-15deg); position: absolute; right: 40px; margin-top: -40px; }
    .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  </style>
</head>
<body>
  <div style="display:flex;justify-content:space-between;align-items:start;border-bottom:2px solid #2563eb;padding-bottom:16px;margin-bottom:24px;position:relative">
    <div>
      <h1 style="color:#2563eb">SendQuote</h1>
      <p style="color:#64748b;font-size:12px">Contract Agreement</p>
    </div>
    <div style="text-align:right">
      <p style="font-weight:bold;font-size:18px">${data.quoteNumber}</p>
      <p style="color:#64748b;font-size:12px">Date: ${new Date().toLocaleDateString()}</p>
    </div>
  </div>

  <h2>Contract Details</h2>
  <table>
    <tr><td style="width:120px;color:#64748b">Client</td><td><strong>${data.clientName}</strong></td></tr>
    ${data.clientEmail ? `<tr><td style="color:#64748b">Email</td><td>${data.clientEmail}</td></tr>` : ""}
    <tr><td style="color:#64748b">Provider</td><td><strong>${data.businessName}</strong></td></tr>
  </table>

  <h2>Services & Pricing</h2>
  <table>
    <thead>
      <tr><th>Description</th><th style="text-align:center">Qty</th><th style="text-align:right">Rate</th><th style="text-align:right">Amount</th></tr>
    </thead>
    <tbody>
      ${itemsRows}
    </tbody>
  </table>

  <div style="text-align:right;margin-top:8px">
    <p>Subtotal: <strong>$${data.subtotal.toFixed(2)}</strong></p>
    ${data.gstRate > 0 ? `<p>GST (${data.gstRate}%): <strong>$${data.gstAmount.toFixed(2)}</strong></p>` : ""}
    <p style="font-size:18px;font-weight:bold;border-top:2px solid #2563eb;padding-top:8px">Total: $${data.total.toFixed(2)}</p>
  </div>

  ${data.notes ? `<h2>Notes</h2><p>${data.notes}</p>` : ""}
  ${data.terms ? `<h2>Terms & Conditions</h2><p>${data.terms}</p>` : ""}

  <h2>Signature</h2>
  <div class="signature-box">
    <p>Signed by: <strong>${data.signatoryName}</strong></p>
    <p>Date: ${new Date(data.signedAt).toLocaleString()}</p>
    <p>IP: Recorded</p>
    <div style="text-align:center;margin-top:8px">
      <span style="font-family:'Brush Script MT',cursive;font-size:28px">${data.signatoryName}</span>
    </div>
  </div>

  ${data.validUntil ? `<p style="color:#64748b;font-size:12px;margin-top:16px">This contract is valid until ${new Date(data.validUntil).toLocaleDateString()}.</p>` : ""}

  <div class="footer">
    <p>Generated by SendQuote — This is a legally binding electronic signature.</p>
    <p>Contract ID: ${data.quoteNumber} | IP logged and timestamped</p>
  </div>
</body>
</html>`;
}
